[mitrap000]
 
city = "Athens - Piraeus - CE"
tz = "Europe/Athens"
ypen = 2
start = "2025-06-02"
end = "2025-10-02"
 
co2_com1 = { name = "CO2", file = "CO2/Data/COM1_Log_*.txt", head = 0 }
ops = { name = "OPS", file = "OPS/Piraeus*.csv", head = 15 }
nanodust = { name = "Nanodust", file = "Nanodust/AirPN10_Software/Test/*1HzData.csv", head = 1 }
ma200 = { name = "MA 200", file = "MA200/MA200_Log_*.txt", head = 0 }
com1 = { name = "Flow Meter Valve COM1", file = "MStack_Flow_Meter_Valve_RHT/COM1_Log_*", head = 0 }
 
 
[mitrap001]
 
city = "Athens - Aristotelous - CE"
tz = "Europe/Athens"
ypen = 9
start = "2025-06-27"
end = "2025-10-02"
 
co2_com1 = { name = "CO2", file = "mitrap1/CO2/Data/COM1_Log_*.txt", head = 0 }
nanodust = { name = "Nanodust", file = "mitrap1/Nanodust/AirPN10_Software/Test/*1HzData.csv", head = 1 }
ma200 = { name = "MA 200", file = "mitrap1/MA200/MA200_Log_*.txt", head = 0 }
com1 = { name = "Flow Meter Valve COM1", file = "mitrap1/MStack_Flow_Meter_Valve_RHT/COM1_Log_*", head = 0 }


[mitrap006]

city = "Athens - Patission - HR"
tz = "Europe/Athens"
ypen = 1
start = "2025-04-14"
end = "2025-10-02"

co2 = { name = "GMP343", file = "CO2/COM2_Log_*.txt", head = 0, pri=1 }
com2 = { name = "Flow Meter Valve COM2", file = "MStack_Flow_Meter_Valve_RHT/COM2_Log_*", head = 0, pri=1 }
ae31 = { name = "AE 31", file = "sambashare/AE31/mitrap/*.csv", head = 0, pri=1 }
mpss = { name = "MPSS", file = "sambashare/MPSS_ATH/inverted/*.inv", head = 0, pri=1 }

uf_valve = { name = "Flow Meter Valve COM1", file = "MStack_Flow_Meter_Valve_RHT/COM1_Log_*", head = 0, pri=0, tz = "UTC" }
#cpc_a20 = { name = "CPC A20", file = "sambashare/cpc_A20/*.dat", head = 0, pri=1 }
uf_cpc3772 = { name = "CPC 3772", file = "sambashare/cpc_3772_Patision/patision_*.txt", head = 0, pri=1 }

pm_grimm = { name = "Grimm OPC", file = "sambashare/GrimmOPC107/*", head = 0, pri=1 }
 
