[mitrap000]
 
city = "Athens - Piraeus - CE"
tz = "Europe/Athens"
ypen = 2
start = "2025-06-02"
end = "2025-10-02"
bucket = "pkg000"
 
co2_com1 = { name = "CO2", file = "CO2/Data/COM1_Log_*.txt", pri = 1, tz = "UTC" }
pm_ops = { name = "OPS", file = "OPS/Piraeus*.csv", pri = 1, tz = "UTC" }
nanodust = { name = "Nanodust", file = "Nanodust/AirPN10_Software/Test/*1HzData.csv", pri = 1, tz = "UTC" }

uf_valve = { name = "Flow Meter Valve COM1", file = "MStack_Flow_Meter_Valve_RHT/COM1_Log_*", pri = 0, tz = "UTC" }
ma200 = { name = "MA 200", file = "MA200/MA200_Log_*.txt", pri = 1, tz = "UTC" }
 
 
[mitrap001]
 
city = "Athens - Aristotelous - CE"
tz = "Europe/Athens"
ypen = 9
start = "2025-06-27"
end = "2025-10-02"
bucket = "pkg000"
 
co2_com1 = { name = "CO2", file = "mitrap1/CO2/Data/COM1_Log_*.txt", pri = 1, tz = "UTC" }
pm_pplus = { name = "OPS", file = "mitrap1/PM_Monitor/ParticlePlus94_PM_MITRAP_*.csv", pri=1, tz = "UTC" }
nanodust = { name = "Nanodust", file = "mitrap1/Nanodust/AirPN10_Software/Test/*1HzData.csv", pri = 1, tz = "UTC" }
 
uf_valve = { name = "Flow Meter Valve COM1", file = "mitrap1/MStack_Flow_Meter_Valve_RHT/COM1_Log_*", pri = 0, tz = "UTC" }
ma200 = { name = "MA 200", file = "mitrap1/MA200/MA200_Log_*.txt", pri=1, tz = "UTC" }


[mitrap006]

city = "Athens - Patission - HR"
tz = "Europe/Athens"
ypen = 1
start = "2025-04-14"
end = "2025-10-02"
bucket = "pkg000"

co2 = { name = "GMP343", file = "CO2/COM2_Log_*.txt", pri=1, tz = "UTC" }
com2 = { name = "Flow Meter Valve COM2", file = "MStack_Flow_Meter_Valve_RHT/COM2_Log_*", pri=1, tz = "UTC" }
ae31 = { name = "AE 31", file = "sambashare/AE31/mitrap/*.csv", pri=1, tz = "UTC" }
mpss = { name = "MPSS", file = "sambashare/MPSS_ATH/inverted/*.inv", pri=1 }

uf_valve = { name = "Flow Meter Valve COM1", file = "MStack_Flow_Meter_Valve_RHT/COM1_Log_*", pri=0, tz = "UTC" }
cpc_a20 = { name = "CPC A20", file = "sambashare/cpc_A20/*.dat", pri=1, tz = "UTC" }

pm_grimm = { name = "Grimm OPC", file = "sambashare/GrimmOPC107/*", pri=1, tz = "UTC" }

org_acsm = { name = "ACSM", file = "sambashare/ACSM/SoFi/TACSM*.itx", pri=1 }
inorg_xact = { name = "XACT", file = "sambashare/XACT/E/Sample*csv", pri=1 }

