
[mitrap000]

city = "Athens - Piraeus - CE"

co2 = { name = "CO2", file = "CO2/Data/COM2_Log_*.txt", head = 0 }

ops = { name = "OPS", file = "OPS/Piraeus*.csv", head = 15 }

nanodust = { name = "Nanodust", file = "Nanodust/AirPN10_Software/Test/*1HzData.csv", head = 1 }

ma200 = { name = "MA 200", file = "MA200/MA200_Log_*.txt", head = 0 }

com1 = { name = "Flow Meter Valve COM1", file = "MStack_Flow_Meter_Valve_RHT/COM1_Log_*", head = 0 }


[mitrap001]

city = "Athens - Aristotelous - CE"

co2_com = { name = "CO2", file = "mitrap1/CO2/Data/COM2_Log_*.txt", head = 0 }

nanodust = { name = "Nanodust", file = "mitrap1/Nanodust/AirPN10_Software/Test/*1HzData.csv", head = 1 }

ma200 = { name = "MA 200", file = "mitrap1/MA200/MA200_Log_*.txt", head = 0 }

com1 = { name = "Flow Meter Valve COM1", file = "mitrap1/MStack_Flow_Meter_Valve_RHT/COM1_Log_*", head = 0 }

#particle+ = { name = "particle+", file = "mitrap1/PM_Monitor/ParticlePlus94_PM_MITRAP_*.csv", head = 5 }

[mitrap006]

city = "Athens - Patission - HR"

com1 = { name = "Flow Meter Valve COM1", file = "MStack_Flow_Meter_Valve_RHT/COM1_Log_*", head = 0 }
co2 = { name = "CO2", file = "CO2/COM2_Log_*.txt", head = 0 }

[mitrap006.com2]
name = "Flow Meter Valve COM2"
file = "MStack_Flow_Meter_Valve_RHT/COM2_Log_*"
head = 0

[mitrap006.ae31]
name = "AE 31" 
file = "sambashare/AE31/mitrap/*.csv"
head = 0

[mitrap006.mpss]
name = "MPSS" 
file = "sambashare/MPSS_ATH/inverted/*.inv"
head = 0

[mitrap006.cpc_a20]
name = "CPC A20"
file = "sambashare/cpc_A20/*.dat"
head = 0

[mitrap006.li_cor]
name = "LiCor"
file = "sambashare/Li_Cor/*.txt"
head = 2

[mitrap006.grimm]
name = "Grimm OPC"
file = "sambashare/GrimmOPC107/*"
head = 0



[mitrap004]

city = "Rotterdam - Statenweg - CE"

co2_modbus = { name = "CO2", file = "CURRENT/CO2/*_co2_log.txt", head = 0 }

#particle+ = { name = "particle+", file = "CURRENT/OPS/start_2025*.csv", head = 1 }

nanodust = { name = "Nanodust", file = "CURRENT/NanoDust/*1HzData.csv", head = 1 }

ma200 = { name = "MA 200", file = "CURRENT/MA/MA200_Log_*.txt", head = 0 }

#com1 = { name = "Flow Meter Valve COM1", file = "CURRENT/RH-T_p_valve/*Device1_log.txt", head = 5 }


[mitrap005]

city = "Rotterdam - Hoek van Holland - CE"

co2_modbus = { name = "CO2", file = "CURRENT/CO2/*_co2_log.txt", head = 0 }

nanodust = { name = "Nanodust", file = "CURRENT/NanoDust/*1HzData.csv", head = 1 }

#com1 = { name = "Flow Meter Valve COM1", file = "CURRENT/RH-T_p_valve/*Device1_log.txt", head = 1 }



[mitrap009]

city = "Rotterdam - Hoek van Holland - HR"

[mitrap009.li_cor]
name = "LiCor"
file = "mitrap009/CO2/*.txt"
head = 2

[mitrap009.mpss2]
name = "SMPS"
file = "mitrap009/Z_SMPS/*auto_exportLevel1.txt"
head = 24


[mitrap002]

city = "Florence – Lavagnini – CE"

co2_modbus = { name = "CO2", file = "CURRENT/CO2/*_co2_log.txt", head = 0 }

#particle+ = { name = "particle+", file = "CURRENT/OPS/start_2025*.csv", head = 1 }

nanodust = { name = "Nanodust", file = "CURRENT/NanoDust/*1HzData.csv", head = 1 }

ma200 = { name = "MA 200", file = "CURRENT/MA/MA200_Log_*.txt", head = 0 }

com1 = { name = "Flow Meter Valve COM1", file = "CURRENT/RH-T_p_valve/*Device1_log.txt", head = 5 }


[mitrap003]

city = "Florence - Ponte alle Mosse - CE"

co2_modbus = { name = "CO2", file = "CURRENT/CO2/*_co2_log.txt", head = 0 }

nanodust = { name = "Nanodust", file = "CURRENT/NanoDust/*1HzData.csv", head = 1 }

com1 = { name = "Flow Meter Valve COM1", file = "CURRENT/RH-T_p_valve/*Device1_log.txt", head = 1 }

ma200 = { name = "MA 200", file = "CURRENT/MA/MA200_Log_*.txt", head = 0 }



[mitrap010]

city = "Florence - HR"

[mitrap010.com1]
name = "Flow Meter Valve COM1"
file = "VALVE/*.txt"
head = 0

[mitrap010.ae36]
name = "AE 31" 
file = "AE36/*.raw"
head = 1

[mitrap010.mpss3]
name = "SMPS" 
file = "SMPS/*.inv"
head = 0

[mitrap010.cpc_3750]
name = "CPC 3750"
file = "CPC/*.raw"
head = 1

[mitrap010.mass]
name = "Cycl_conc"
file = "MASS/*.raw"
head = 1
