
[mitrap000]

city = "Copenhagen - Taarnby - CE"
ypen = 2

co2_com1 = { name = "GMP252", file = "CO2/Data/COM1_Log_*.txt", head = 0 }

pm_ops = { name = "OPS", file = "OPS/Piraeus*.csv", head = 15 }

nanodust = { name = "Nanodust", file = "Nanodust/AirPN10_Software/Test/*1HzData.csv", head = 1 }

ma200 = { name = "MA 200", file = "MA200/MA200_Log_*.txt", head = 0 }

com1 = { name = "Flow Meter Valve COM1", file = "MStack_Flow_Meter_Valve_RHT/COM1_Log_*", head = 0 }


[mitrap001]

city = "Aarhus - Port - CE"

co2_com1 = { name = "GMP252", file = "mitrap1/CO2/Data/COM1_Log_*.txt", head = 0, pri=1 }

pm_pplus = { name = "OPS", file = "mitrap1/PM_Monitor/ParticlePlus94_PM_MITRAP_*.csv", head = 5, pri=1 }

nanodust = { name = "Nanodust", file = "mitrap1/Nanodust/AirPN10_Software/data/*1HzData.csv", head = 1, pri=1 }

ma200 = { name = "MA 200", file = "mitrap1/MA200/MA200_Log_*.txt", head = 0, pri=1 }

com1 = { name = "Flow Meter Valve COM1", file = "mitrap1/MStack_Flow_Meter_Valve_RHT/COM1_Log_*", head = 0, pri=1 }



[mitrap004]

city = "Rotterdam - Statenweg - CE"

nanodust = { name = "Nanodust", file = "CURRENT/NanoDust/*1HzData.csv", head = 1 }

ma200 = { name = "MA 200", file = "CURRENT/MA/MA200_Log_*.txt", head = 0 }

co2_modbus = { name = "GMP252", file = "CURRENT/CO2/*_co2_log.txt", head = 0 }

pm_pplus = { name = "ParticlePlus", file = "CURRENT/OPS/start_*.csv", head = 5 }


[mitrap005]

city = "Rotterdam - Hoek van Holland - CE"

nanodust = { name = "Nanodust", file = "CURRENT/NanoDust/*1HzData.csv", head = 1 }

co2_modbus = { name = "GMP252", file = "CURRENT/CO2/*_co2_log.txt", head = 0 }

pm_pplus = { name = "ParticlePlus", file = "CURRENT/OPS/start_*.csv", head = 5 }


[mitrap006]

city = "Athens - Patission - HR"
ypen = 1

com1 = { name = "Flow Meter Valve COM1", file = "MStack_Flow_Meter_Valve_RHT/COM1_Log_*", head = 0 }

co2 = { name = "GMP343", file = "CO2/COM2_Log_*.txt", head = 0 }

com2 = { name = "Flow Meter Valve COM2", file = "MStack_Flow_Meter_Valve_RHT/COM2_Log_*", head = 0 }

ae31 = { name = "AE 31", file = "sambashare/AE31/mitrap/*.csv", head = 0 }

mpss = { name = "MPSS", file = "sambashare/MPSS_ATH/inverted/*.inv", head = 0 }

cpc_a20 = { name = "CPC A20", file = "sambashare/cpc_A20/*.dat", head = 0 }

pm_grimm = { name = "Grimm OPC", file = "sambashare/GrimmOPC107/*", head = 0 }


[mitrap009]

city = "Rotterdam - Hoek van Holland - HR"

co2_licor = { name = "LiCor", file = "mitrap009/CO2/*.txt", head = 2 }

org_acsm = { name = "ACSM", file = "mitrap009/ACSM/ExportData_new/Rotterdam_ACSM-140294_RTdata_*.itx", head = -1 }

